packages:
  - apps/*
  - packages/*
  - infra

onlyBuiltDependencies:
  - lefthook

overrides:
  '@hono/node-server@<1.19.10': '>=1.19.10'
  hono@<4.12.4: '>=4.12.4'
  minimatch@>=10.0.0 <10.2.1: '>=10.2.1'
  minimatch@>=10.0.0 <10.2.3: '>=10.2.3'
  rollup@>=4.0.0 <4.59.0: '>=4.59.0'
  undici@<6.23.0: '>=6.23.0'
