import type { UUID } from 'node:crypto';
import { z } from 'zod';

export const UuidSchema = z.uuid().transform((x) => x as UUID);

export const PlatformAttachmentSchema = z.object({
  url: z.string(),
  contentType: z.string().nullable(),
  data: z.string().optional(),
});

export const PlatformMessageSchema = z.object({
  authorId: z.string(),
  authorDisplayName: z.string(),
  authorIsBot: z.boolean(),
  content: z.string(),
  createdTimestamp: z.number(),
  attachments: z.array(PlatformAttachmentSchema),
  messageId: z.string(),
});

// --- Shared building blocks ---

export const ReplySchema = z.object({
  correlationId: z.string().describe('Correlation ID generated by brain to track this reply through the delivery pipeline'),
  replyTo: z.string().optional().describe('authorId to reply to (creates a Discord reply thread)'),
  ping: z.boolean().optional().describe('Whether the reply should ping/mention the target user'),
  message: z.string().describe('The message content to send'),
});

// --- Capabilities ---

export enum BotCapability {
  Web = 'WEB',
  Workspace = 'WORKSPACE',
}

export const CapabilitiesSchema = z
  .object({
    [BotCapability.Web]: z.boolean(),
    [BotCapability.Workspace]: z.boolean(),
  })
  .partial()
  .optional();

// --- Request schemas ---

export const BotIdentitySchema = z.object({
  botUserId: z.string().optional(),
  botUsername: z.string().optional(),
});

export const RespondRequestSchema = z
  .object({
    messages: z.array(PlatformMessageSchema),
    capabilities: CapabilitiesSchema,
    callbackUrl: z.url(),
  })
  .extend(BotIdentitySchema.shape);

export const UnpromptedTriggerSchema = z.enum(['workplay', 'random-thought']);

export const UnpromptedRequestSchema = z
  .object({
    trigger: UnpromptedTriggerSchema,
    capabilities: CapabilitiesSchema,
  })
  .extend(BotIdentitySchema.shape);

export const DirectRequestSchema = z.object({
  prompt: z.string(),
  capabilities: CapabilitiesSchema,
});

export const ResetRequestSchema = z.object({
  messages: z.array(PlatformMessageSchema),
});

export const SessionSetRequestSchema = z.object({
  sessionId: UuidSchema,
});

export const CompactRequestSchema = z.object({
  resumeSessionAt: UuidSchema.optional(),
});

// --- Response schemas ---

export const RespondResponseSchema = z.object({
  replies: z.array(ReplySchema),
  error: z.string().optional(),
});

export const UnpromptedResponseSchema = z.object({
  replies: z.array(ReplySchema),
  spoke: z.boolean(),
  error: z.string().optional(),
});

export const DirectResponseSchema = z.object({
  result: z.string(),
  error: z.string().optional(),
});

export const CompactResponseSchema = z.object({
  result: z.string(),
  error: z.string().optional(),
});

export const ResetResponseSchema = z.object({
  result: z.string(),
  error: z.string().optional(),
});

export const HealthResponseSchema = z.object({
  status: z.literal('ok'),
});

export const PingResponseSchema = z.object({
  result: z.string(),
  error: z.string().optional(),
});

export const SessionResponseSchema = z.object({
  sessionId: z.string().nullable(),
});

export const VersionResponseSchema = z.object({
  buildDate: z.string(),
  branch: z.string(),
  sha: z.string(),
  shortSha: z.string(),
  commitDate: z.string(),
  version: z.string(),
  node: z.string(),
  CONTAINER_APP_REPLICA_NAME: z.string(),
  CONTAINER_APP_REVISION: z.string(),
});

// --- Callback API ---

export const CallbackRequestSchema = z.discriminatedUnion('type', [
  z.object({
    type: z.literal('typing').describe('Heartbeat — brain sends periodically to keep the typing indicator active'),
  }),
  z.object({
    type: z.literal('message').describe('Final delivery — brain sends once with all replies when processing is complete'),
    replies: z.array(ReplySchema).describe('Replies to dispatch. Ears calculates typing delays between them.'),
  }),
]);

export const DeliveredMessageSchema = z.object({
  discordMessageId: z.string().describe('The Discord message ID assigned to the sent message'),
  correlationId: z.string().describe('Correlation ID from Reply.correlationId — traces this delivered message back to the brain reply'),
  timestamp: z.iso.datetime().describe('ISO 8601 timestamp of when the message was delivered to Discord'),
  message: z.string().describe('The actual message content sent (may be chunked from the original reply)'),
});

export const CallbackResponseSchema = z.object({
  delivered: z.array(DeliveredMessageSchema).describe('All messages delivered to Discord, in send order. One reply may produce multiple messages due to chunking.'),
});
